/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.Dynamic;

public interface RNSVGFeConvolveMatrixManagerInterface<T extends View> {
  void setX(T view, Dynamic value);
  void setY(T view, Dynamic value);
  void setWidth(T view, Dynamic value);
  void setHeight(T view, Dynamic value);
  void setResult(T view, @Nullable String value);
  void setIn1(T view, @Nullable String value);
  void setOrder(T view, Dynamic value);
  void setKernelMatrix(T view, Dynamic value);
  void setDivisor(T view, Dynamic value);
  void setBias(T view, Dynamic value);
  void setTargetX(T view, Dynamic value);
  void setTargetY(T view, Dynamic value);
  void setEdgeMode(T view, @Nullable String value);
  void setPreserveAlpha(T view, boolean value);
}
