/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;

public interface RNSVGSvgViewManagerInterface<T extends View> {
  void setMinX(T view, float value);
  void setMinY(T view, float value);
  void setVbWidth(T view, float value);
  void setVbHeight(T view, float value);
  void setAlign(T view, @Nullable String value);
  void setMeetOrSlice(T view, int value);
}
