/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.Dynamic;

public interface RNSVGFeTurbulenceManagerInterface<T extends View> {
  void setX(T view, Dynamic value);
  void setY(T view, Dynamic value);
  void setWidth(T view, Dynamic value);
  void setHeight(T view, Dynamic value);
  void setResult(T view, @Nullable String value);
  void setBaseFrequency(T view, Dynamic value);
  void setNumOctaves(T view, Dynamic value);
  void setSeed(T view, Dynamic value);
  void setStitchTiles(T view, @Nullable String value);
  void setType(T view, @Nullable String value);
}
