// swift-tools-version: 6.0
// AUTO-SCAFFOLDED by react-native spm scaffold — safe to edit & commit via patch-package.
// AUTO-SCAFFOLDED-VERSION: 19
// Cache slot: 0.87.1/dual-flavor
// Edit the contents below if needed and re-run `npx patch-package <dep-name>`
// to persist across `npm install`. To regenerate from the podspec, remove
// this file (or just this marker) and re-run `npx react-native spm scaffold`.
//
// Package references are plain relative paths, computed when this file was
// scaffolded. They stay correct because the file is re-scaffolded per app
// and cache slot, and any node_modules relayout reinstalls this package
// (dropping the file) anyway.

import PackageDescription

let package = Package(
    name: "ReactNativeSvg",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "ReactNativeSvg", targets: ["ReactNativeSvg"]),
    ],
    dependencies: [
        .package(name: "ReactNative", path: "../../../../xcframeworks"),
        .package(name: "React-GeneratedCode", path: "../../../ios"),
    ],
    targets: [
        .target(
            name: "ReactNativeSvg",
            dependencies: [.product(name: "ReactHeaders", package: "ReactNative"), .product(name: "ReactNativeHeaders", package: "ReactNative"), .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"), .product(name: "ReactAppHeaders", package: "React-GeneratedCode")],
            path: ".",
            sources: [
                "apple/Brushes/RNSVGBrush.h",
                "apple/Brushes/RNSVGBrush.mm",
                "apple/Brushes/RNSVGBrushType.h",
                "apple/Brushes/RNSVGContextBrush.h",
                "apple/Brushes/RNSVGContextBrush.mm",
                "apple/Brushes/RNSVGPainter.h",
                "apple/Brushes/RNSVGPainter.mm",
                "apple/Brushes/RNSVGPainterBrush.h",
                "apple/Brushes/RNSVGPainterBrush.mm",
                "apple/Brushes/RNSVGSolidColorBrush.h",
                "apple/Brushes/RNSVGSolidColorBrush.mm",
                "apple/Elements/RNSVGClipPath.h",
                "apple/Elements/RNSVGClipPath.mm",
                "apple/Elements/RNSVGDefs.h",
                "apple/Elements/RNSVGDefs.mm",
                "apple/Elements/RNSVGForeignObject.h",
                "apple/Elements/RNSVGForeignObject.mm",
                "apple/Elements/RNSVGGroup.h",
                "apple/Elements/RNSVGGroup.mm",
                "apple/Elements/RNSVGImage.h",
                "apple/Elements/RNSVGImage.mm",
                "apple/Elements/RNSVGLinearGradient.h",
                "apple/Elements/RNSVGLinearGradient.mm",
                "apple/Elements/RNSVGMarker.h",
                "apple/Elements/RNSVGMarker.mm",
                "apple/Elements/RNSVGMask.h",
                "apple/Elements/RNSVGMask.mm",
                "apple/Elements/RNSVGPath.h",
                "apple/Elements/RNSVGPath.mm",
                "apple/Elements/RNSVGPattern.h",
                "apple/Elements/RNSVGPattern.mm",
                "apple/Elements/RNSVGRadialGradient.h",
                "apple/Elements/RNSVGRadialGradient.mm",
                "apple/Elements/RNSVGSvgView.h",
                "apple/Elements/RNSVGSvgView.mm",
                "apple/Elements/RNSVGSymbol.h",
                "apple/Elements/RNSVGSymbol.mm",
                "apple/Elements/RNSVGUse.h",
                "apple/Elements/RNSVGUse.mm",
                "apple/Filters/MetalCI/RNSVGArithmeticFilter.h",
                "apple/Filters/MetalCI/RNSVGArithmeticFilter.mm",
                "apple/Filters/MetalCI/RNSVGCompositeXor.h",
                "apple/Filters/MetalCI/RNSVGCompositeXor.mm",
                "apple/Filters/MetalCI/RNSVGCustomFilter.h",
                "apple/Filters/MetalCI/RNSVGCustomFilter.mm",
                "apple/Filters/RNSVGBlendMode.h",
                "apple/Filters/RNSVGColorMatrixType.h",
                "apple/Filters/RNSVGCompositeOperator.h",
                "apple/Filters/RNSVGEdgeMode.h",
                "apple/Filters/RNSVGFeBlend.h",
                "apple/Filters/RNSVGFeBlend.mm",
                "apple/Filters/RNSVGFeColorMatrix.h",
                "apple/Filters/RNSVGFeColorMatrix.mm",
                "apple/Filters/RNSVGFeComposite.h",
                "apple/Filters/RNSVGFeComposite.mm",
                "apple/Filters/RNSVGFeFlood.h",
                "apple/Filters/RNSVGFeFlood.mm",
                "apple/Filters/RNSVGFeGaussianBlur.h",
                "apple/Filters/RNSVGFeGaussianBlur.mm",
                "apple/Filters/RNSVGFeMerge.h",
                "apple/Filters/RNSVGFeMerge.mm",
                "apple/Filters/RNSVGFeOffset.h",
                "apple/Filters/RNSVGFeOffset.mm",
                "apple/Filters/RNSVGFilter.h",
                "apple/Filters/RNSVGFilter.mm",
                "apple/Filters/RNSVGFilterPrimitive.h",
                "apple/Filters/RNSVGFilterPrimitive.mm",
                "apple/Filters/RNSVGFilterRegion.h",
                "apple/Filters/RNSVGFilterRegion.mm",
                "apple/RNSVGContainer.h",
                "apple/RNSVGNode.h",
                "apple/RNSVGNode.mm",
                "apple/RNSVGRenderable.h",
                "apple/RNSVGRenderable.mm",
                "apple/RNSVGRenderableModule.h",
                "apple/RNSVGRenderableModule.mm",
                "apple/RNSVGSvgViewModule.h",
                "apple/RNSVGSvgViewModule.mm",
                "apple/RNSVGUIKit.h",
                "apple/RNSVGUIKit.macos.mm",
                "apple/Shapes/RNSVGCircle.h",
                "apple/Shapes/RNSVGCircle.mm",
                "apple/Shapes/RNSVGEllipse.h",
                "apple/Shapes/RNSVGEllipse.mm",
                "apple/Shapes/RNSVGLine.h",
                "apple/Shapes/RNSVGLine.mm",
                "apple/Shapes/RNSVGRect.h",
                "apple/Shapes/RNSVGRect.mm",
                "apple/Text/RNSVGFontData.h",
                "apple/Text/RNSVGFontData.mm",
                "apple/Text/RNSVGGlyphContext.h",
                "apple/Text/RNSVGGlyphContext.mm",
                "apple/Text/RNSVGPropHelper.h",
                "apple/Text/RNSVGPropHelper.mm",
                "apple/Text/RNSVGTSpan.h",
                "apple/Text/RNSVGTSpan.mm",
                "apple/Text/RNSVGText.h",
                "apple/Text/RNSVGText.mm",
                "apple/Text/RNSVGTextPath.h",
                "apple/Text/RNSVGTextPath.mm",
                "apple/Text/RNSVGTextProperties.h",
                "apple/Text/RNSVGTextProperties.mm",
                "apple/Text/RNSVGTopAlignedLabel.h",
                "apple/Text/RNSVGTopAlignedLabel.ios.mm",
                "apple/Text/RNSVGTopAlignedLabel.macos.mm",
                "apple/Utils/RCTConvert+RNSVG.h",
                "apple/Utils/RCTConvert+RNSVG.mm",
                "apple/Utils/RNSVGBezierElement.h",
                "apple/Utils/RNSVGBezierElement.mm",
                "apple/Utils/RNSVGCGFCRule.h",
                "apple/Utils/RNSVGConvert.h",
                "apple/Utils/RNSVGConvert.mm",
                "apple/Utils/RNSVGFabricConversions.h",
                "apple/Utils/RNSVGLength.h",
                "apple/Utils/RNSVGLength.mm",
                "apple/Utils/RNSVGMarkerPosition.h",
                "apple/Utils/RNSVGMarkerPosition.mm",
                "apple/Utils/RNSVGMaskType.h",
                "apple/Utils/RNSVGPathMeasure.h",
                "apple/Utils/RNSVGPathMeasure.mm",
                "apple/Utils/RNSVGPathParser.h",
                "apple/Utils/RNSVGPathParser.mm",
                "apple/Utils/RNSVGRenderUtils.h",
                "apple/Utils/RNSVGRenderUtils.mm",
                "apple/Utils/RNSVGUnits.h",
                "apple/Utils/RNSVGVBMOS.h",
                "apple/Utils/RNSVGVectorEffect.h",
                "apple/Utils/RNSVGViewBox.h",
                "apple/Utils/RNSVGViewBox.mm",
                "apple/ViewManagers/RNSVGCircleManager.h",
                "apple/ViewManagers/RNSVGCircleManager.mm",
                "apple/ViewManagers/RNSVGClipPathManager.h",
                "apple/ViewManagers/RNSVGClipPathManager.mm",
                "apple/ViewManagers/RNSVGDefsManager.h",
                "apple/ViewManagers/RNSVGDefsManager.mm",
                "apple/ViewManagers/RNSVGEllipseManager.h",
                "apple/ViewManagers/RNSVGEllipseManager.mm",
                "apple/ViewManagers/RNSVGFeBlendManager.h",
                "apple/ViewManagers/RNSVGFeBlendManager.mm",
                "apple/ViewManagers/RNSVGFeColorMatrixManager.h",
                "apple/ViewManagers/RNSVGFeColorMatrixManager.mm",
                "apple/ViewManagers/RNSVGFeCompositeManager.h",
                "apple/ViewManagers/RNSVGFeCompositeManager.mm",
                "apple/ViewManagers/RNSVGFeFloodManager.h",
                "apple/ViewManagers/RNSVGFeFloodManager.mm",
                "apple/ViewManagers/RNSVGFeGaussianBlurManager.h",
                "apple/ViewManagers/RNSVGFeGaussianBlurManager.mm",
                "apple/ViewManagers/RNSVGFeMergeManager.h",
                "apple/ViewManagers/RNSVGFeMergeManager.mm",
                "apple/ViewManagers/RNSVGFeOffsetManager.h",
                "apple/ViewManagers/RNSVGFeOffsetManager.mm",
                "apple/ViewManagers/RNSVGFilterManager.h",
                "apple/ViewManagers/RNSVGFilterManager.mm",
                "apple/ViewManagers/RNSVGFilterPrimitiveManager.h",
                "apple/ViewManagers/RNSVGFilterPrimitiveManager.mm",
                "apple/ViewManagers/RNSVGForeignObjectManager.h",
                "apple/ViewManagers/RNSVGForeignObjectManager.mm",
                "apple/ViewManagers/RNSVGGroupManager.h",
                "apple/ViewManagers/RNSVGGroupManager.mm",
                "apple/ViewManagers/RNSVGImageManager.h",
                "apple/ViewManagers/RNSVGImageManager.mm",
                "apple/ViewManagers/RNSVGLineManager.h",
                "apple/ViewManagers/RNSVGLineManager.mm",
                "apple/ViewManagers/RNSVGLinearGradientManager.h",
                "apple/ViewManagers/RNSVGLinearGradientManager.mm",
                "apple/ViewManagers/RNSVGMarkerManager.h",
                "apple/ViewManagers/RNSVGMarkerManager.mm",
                "apple/ViewManagers/RNSVGMaskManager.h",
                "apple/ViewManagers/RNSVGMaskManager.mm",
                "apple/ViewManagers/RNSVGNodeManager.h",
                "apple/ViewManagers/RNSVGNodeManager.mm",
                "apple/ViewManagers/RNSVGPathManager.h",
                "apple/ViewManagers/RNSVGPathManager.mm",
                "apple/ViewManagers/RNSVGPatternManager.h",
                "apple/ViewManagers/RNSVGPatternManager.mm",
                "apple/ViewManagers/RNSVGRadialGradientManager.h",
                "apple/ViewManagers/RNSVGRadialGradientManager.mm",
                "apple/ViewManagers/RNSVGRectManager.h",
                "apple/ViewManagers/RNSVGRectManager.mm",
                "apple/ViewManagers/RNSVGRenderableManager.h",
                "apple/ViewManagers/RNSVGRenderableManager.mm",
                "apple/ViewManagers/RNSVGSvgViewManager.h",
                "apple/ViewManagers/RNSVGSvgViewManager.mm",
                "apple/ViewManagers/RNSVGSymbolManager.h",
                "apple/ViewManagers/RNSVGSymbolManager.mm",
                "apple/ViewManagers/RNSVGTSpanManager.h",
                "apple/ViewManagers/RNSVGTSpanManager.mm",
                "apple/ViewManagers/RNSVGTextManager.h",
                "apple/ViewManagers/RNSVGTextManager.mm",
                "apple/ViewManagers/RNSVGTextPathManager.h",
                "apple/ViewManagers/RNSVGTextPathManager.mm",
                "apple/ViewManagers/RNSVGUseManager.h",
                "apple/ViewManagers/RNSVGUseManager.mm",
                "common/cpp/react/renderer/components/rnsvg/RNSVGComponentDescriptors.h",
                "common/cpp/react/renderer/components/rnsvg/RNSVGConcreteShadowNode.h",
                "common/cpp/react/renderer/components/rnsvg/RNSVGImageComponentDescriptor.h",
                "common/cpp/react/renderer/components/rnsvg/RNSVGImageShadowNode.cpp",
                "common/cpp/react/renderer/components/rnsvg/RNSVGImageShadowNode.h",
                "common/cpp/react/renderer/components/rnsvg/RNSVGImageState.cpp",
                "common/cpp/react/renderer/components/rnsvg/RNSVGImageState.h",
                "common/cpp/react/renderer/components/rnsvg/RNSVGLayoutableShadowNode.cpp",
                "common/cpp/react/renderer/components/rnsvg/RNSVGLayoutableShadowNode.h",
                "common/cpp/react/renderer/components/rnsvg/RNSVGShadowNodes.cpp",
                "common/cpp/react/renderer/components/rnsvg/RNSVGShadowNodes.h",
            ],
            publicHeadersPath: "apple",
            cSettings: [.define("REACT_NATIVE_MINOR_VERSION", to: "87"), .headerSearchPath("common/cpp"), .headerSearchPath("apple/Brushes"), .headerSearchPath("apple/Elements"), .headerSearchPath("apple/Filters/MetalCI"), .headerSearchPath("apple/Filters"), .headerSearchPath("apple"), .headerSearchPath("apple/Shapes"), .headerSearchPath("apple/Text"), .headerSearchPath("apple/Utils"), .headerSearchPath("apple/ViewManagers"), .headerSearchPath("common/cpp/react/renderer/components/rnsvg"), .headerSearchPath("."), .unsafeFlags(["-include", "react-native-spm-prefix.h"])],
            cxxSettings: [.define("REACT_NATIVE_MINOR_VERSION", to: "87"), .headerSearchPath("common/cpp"), .headerSearchPath("apple/Brushes"), .headerSearchPath("apple/Elements"), .headerSearchPath("apple/Filters/MetalCI"), .headerSearchPath("apple/Filters"), .headerSearchPath("apple"), .headerSearchPath("apple/Shapes"), .headerSearchPath("apple/Text"), .headerSearchPath("apple/Utils"), .headerSearchPath("apple/ViewManagers"), .headerSearchPath("common/cpp/react/renderer/components/rnsvg"), .headerSearchPath("."), .unsafeFlags(["-include", "react-native-spm-prefix.h"]), .define("DEBUG", .when(configuration: .debug)), .define("NDEBUG", .when(configuration: .release))],
            linkerSettings: [.linkedFramework("UIKit"), .linkedFramework("Foundation"), .linkedFramework("CoreGraphics")]
        ),
    ],
    cxxLanguageStandard: .cxx20
)
