module.exports = {
  dependency: {
    platforms: {
      android: {
        componentDescriptors: [
          'RNSVGCircleComponentDescriptor',
          'RNSVGClipPathComponentDescriptor',
          'RNSVGDefsComponentDescriptor',
          'RNSVGFeBlendComponentDescriptor',
          'RNSVGFeColorMatrixComponentDescriptor',
          'RNSVGFeCompositeComponentDescriptor',
          'RNSVGFeFloodComponentDescriptor',
          'RNSVGFeGaussianBlurComponentDescriptor',
          'RNSVGFeMergeComponentDescriptor',
          'RNSVGFeOffsetComponentDescriptor',
          'RNSVGFilterComponentDescriptor',
          'RNSVGEllipseComponentDescriptor',
          'RNSVGForeignObjectComponentDescriptor',
          'RNSVGGroupComponentDescriptor',
          'RNSVGImageComponentDescriptor',
          'RNSVGLinearGradientComponentDescriptor',
          'RNSVGLineComponentDescriptor',
          'RNSVGMarkerComponentDescriptor',
          'RNSVGMaskComponentDescriptor',
          'RNSVGPathComponentDescriptor',
          'RNSVGPatternComponentDescriptor',
          'RNSVGRadialGradientComponentDescriptor',
          'RNSVGRectComponentDescriptor',
          'RNSVGSvgViewAndroidComponentDescriptor',
          'RNSVGSymbolComponentDescriptor',
          'RNSVGTextComponentDescriptor',
          'RNSVGTextPathComponentDescriptor',
          'RNSVGTSpanComponentDescriptor',
          'RNSVGUseComponentDescriptor',
        ],
        cmakeListsPath: '../android/src/main/jni/CMakeLists.txt',
      },
    },
  },
};
