#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, RNSVGComponentTransferFuncType) {
  SVG_FECOMPONENTTRANSFERFUNC_TYPE_IDENTITY,
  SVG_FECOMPONENTTRANSFERFUNC_TYPE_TABLE,
  SVG_FECOMPONENTTRANSFERFUNC_TYPE_DISCRETE,
  SVG_FECOMPONENTTRANSFERFUNC_TYPE_LINEAR,
  SVG_FECOMPONENTTRANSFERFUNC_TYPE_GAMMA,
};
