typedef CF_ENUM(int32_t, RNSVGCompositeOperator) {
  SVG_FECOMPOSITE_OPERATOR_UNKNOWN,
  SVG_FECOMPOSITE_OPERATOR_OVER,
  SVG_FECOMPOSITE_OPERATOR_IN,
  SVG_FECOMPOSITE_OPERATOR_OUT,
  SVG_FECOMPOSITE_OPERATOR_ATOP,
  SVG_FECOMPOSITE_OPERATOR_XOR,
  SVG_FECOMPOSITE_OPERATOR_ARITHMETIC
};
