typedef CF_ENUM(int32_t, RNSVGBlendMode) {
  SVG_FEBLEND_MODE_UNKNOWN,
  SVG_FEBLEND_MODE_NORMAL,
  SVG_FEBLEND_MODE_MULTIPLY,
  SVG_FEBLEND_MODE_SCREEN,
  SVG_FEBLEND_MODE_DARKEN,
  SVG_FEBLEND_MODE_LIGHTEN,
};
