typedef CF_ENUM(int32_t, RNSVGColorMatrixType) {
  SVG_FECOLORMATRIX_TYPE_UNKNOWN,
  SVG_FECOLORMATRIX_TYPE_MATRIX,
  SVG_FECOLORMATRIX_TYPE_SATURATE,
  SVG_FECOLORMATRIX_TYPE_HUEROTATE,
  SVG_FECOLORMATRIX_TYPE_LUMINANCETOALPHA
};
