#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, RNSVGComponentTransferFuncChannel) {
  SVG_FECOMPONENTTRANSFERFUNC_CHANNEL_UNKNOWN,
  SVG_FECOMPONENTTRANSFERFUNC_CHANNEL_R,
  SVG_FECOMPONENTTRANSFERFUNC_CHANNEL_G,
  SVG_FECOMPONENTTRANSFERFUNC_CHANNEL_B,
  SVG_FECOMPONENTTRANSFERFUNC_CHANNEL_A,
};
