import "Views.idl";

namespace RNSVG
{
  [experimental]
  interface IRenderableFabric
  {
    IRenderableFabric SvgParent;

    void UpdateProperties(Microsoft.ReactNative.IComponentProps props, Microsoft.ReactNative.IComponentProps oldProps, Boolean forceUpdate, Boolean invalidate);
  };

  [experimental]
  [default_interface]
  runtimeclass SvgView : IRenderable, IRenderableFabric, ISvgView
  {
    GroupView Group;
    Microsoft.ReactNative.Color CurrentColor{ get; };
    Microsoft.ReactNative.Composition.Theme Theme { get; };
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass RenderableView : IRenderable, IRenderableFabric, IRenderableView
  {
    SvgView SvgRoot{ get; };
    Microsoft.ReactNative.Color Fill{ get; };
    Microsoft.ReactNative.Color Stroke{ get; };
  };

  [experimental]
  [default_interface]
  runtimeclass RectView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass CircleView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass EllipseView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass LineView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass PathView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass UseView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass ImageView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass GroupView : RenderableView, IGroupView
  {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass TextView : GroupView, ITextView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass TSpanView : TextView, ITSpanView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass DefsView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass SymbolView : GroupView, ISymbolView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass ClipPathView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass MarkerView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass MaskView : GroupView
  {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass BrushView : GroupView, IBrushView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass LinearGradientView : BrushView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass RadialGradientView : BrushView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass PatternView : BrushView
  {
  };
}