import "Views.idl";

namespace RNSVG
{
  [experimental]
  [default_interface]
  runtimeclass SvgView
  {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass RectView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass CircleView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass EllipseView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass LineView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass PathView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass UseView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass ImageView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass GroupView : RenderableView
  {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass TextView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass TSpanView : TextView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass DefsView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass SymbolView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass ClipPathView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass MarkerView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass MaskView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass LinearGradientView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass RadialGradientView : GroupView
  {
  };

  [experimental]
  [default_interface]
  runtimeclass PatternView : GroupView
  {
  };
}