import "RenderableView.idl";

namespace RNSVG
{
    [default_interface]
    runtimeclass GroupView : RenderableView
    {
      GroupView(Microsoft.ReactNative.IReactContext context);
      Windows.Foundation.Collections.IVector<Windows.UI.Xaml.UIElement> Children { get; };

      void RenderGroup(
          Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl canvas,
          Microsoft.Graphics.Canvas.CanvasDrawingSession session);
    };
}
