namespace RNSVG
{
    [bindable]
    [default_interface]
    runtimeclass RectViewManager
      : Microsoft.ReactNative.IViewManager
      , Microsoft.ReactNative.IViewManagerWithNativeProperties
    {
        RectViewManager();
    }
}
