import "GroupView.idl";

namespace RNSVG
{
    interface RenderableView 
    {
      Windows.UI.Color Color;
      void UpdateProperties(Microsoft.ReactNative.IJSValueReader reader);
      void Render(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl canvas, Microsoft.Graphics.Canvas.CanvasDrawingSession session);
      void SetParent(Windows.UI.Xaml.FrameworkElement parent);
    }
}
