namespace RNSVG
{
  enum SVGClass
  {
    RNSVGGroup,
    RNSVGPath,
    RNSVGText,
    RNSVGTSpan,
    RNSVGTextPath,
    RNSVGImage,
    RNSVGCircle,
    RNSVGEllipse,
    RNSVGLine,
    RNSVGRect,
    RNSVGClipPath,
    RNSVGDefs,
    RNSVGUse,
    RNSVGSymbol,
    RNSVGLinearGradient,
    RNSVGRadialGradient,
    RNSVGPattern,
    RNSVGMask,
    RNSVGMarker,
    RNSVGForeignObject,
    Unknown,
  };

  [default_interface]
  unsealed runtimeclass RenderableViewManager
    : Microsoft.ReactNative.IViewManager
    , Microsoft.ReactNative.IViewManagerWithReactContext
    , Microsoft.ReactNative.IViewManagerWithNativeProperties
  {
  }

  [default_interface]
  runtimeclass GroupViewManager
    : RenderableViewManager
    , Microsoft.ReactNative.IViewManagerWithChildren
  {
      GroupViewManager();
  }

  [default_interface]
  runtimeclass RectViewManager : RenderableViewManager
  {
      RectViewManager();
  }

  [default_interface]
  runtimeclass PathViewManager : RenderableViewManager
  {
      PathViewManager();
  }
}
