namespace RNSVG
{
  enum SVGClass
  {
    RNSVGGroup,
    RNSVGPath,
    RNSVGText,
    RNSVGTSpan,
    RNSVGTextPath,
    RNSVGImage,
    RNSVGCircle,
    RNSVGEllipse,
    RNSVGLine,
    RNSVGRect,
    RNSVGClipPath,
    RNSVGDefs,
    RNSVGUse,
    RNSVGSymbol,
    RNSVGLinearGradient,
    RNSVGRadialGradient,
    RNSVGPattern,
    RNSVGMask,
    RNSVGMarker,
    RNSVGForeignObject,
    Unknown,
  };

  [default_interface]
  unsealed runtimeclass RenderableViewManager
    : Microsoft.ReactNative.IViewManager
    , Microsoft.ReactNative.IViewManagerWithReactContext
    , Microsoft.ReactNative.IViewManagerWithNativeProperties
  {
    RenderableViewManager();
  }

  [default_interface]
  runtimeclass RectViewManager : RenderableViewManager
  {
      RectViewManager();
  }

  [default_interface]
  runtimeclass CircleViewManager : RenderableViewManager
  {
      CircleViewManager();
  }

  [default_interface]
  runtimeclass EllipseViewManager : RenderableViewManager
  {
      EllipseViewManager();
  }

  [default_interface]
  runtimeclass LineViewManager : RenderableViewManager
  {
      LineViewManager();
  }

  [default_interface]
  runtimeclass PathViewManager : RenderableViewManager
  {
      PathViewManager();
  }

  [default_interface]
  unsealed runtimeclass GroupViewManager
    : RenderableViewManager
    , Microsoft.ReactNative.IViewManagerWithChildren
  {
      GroupViewManager();
  }

  [default_interface]
  unsealed runtimeclass TextViewManager : GroupViewManager
  {
      TextViewManager();
  }

  [default_interface]
  runtimeclass TSpanViewManager : TextViewManager
  {
      TSpanViewManager();
  }
}
