namespace RNSVG
{
    [default_interface]
    unsealed runtimeclass RenderableView : Windows.UI.Xaml.FrameworkElement
    {
      Windows.UI.Xaml.FrameworkElement SvgParent;
      Windows.UI.Color Fill;
      Single FillOpacity;
      Windows.UI.Color Stroke;
      Single StrokeOpacity;
      Single StrokeWidth;

      void UpdateProperties(Microsoft.ReactNative.IJSValueReader reader);
      void InvalidateCanvas();

      void Render(
        Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl canvas,
        Microsoft.Graphics.Canvas.CanvasDrawingSession session);
    }
}
