namespace RNSVG
{
  enum UnitType
  {
    Unknown,
    Number,
    Percentage,
    EMS,
    EXS,
    PX,
    CM,
    MM,
    PT,
    PC,
  };

  [default_interface]
  runtimeclass SVGLength 
  {
    SVGLength();
    SVGLength(Single param);
    SVGLength(Single param, UnitType type);

    Single Value{get;};
    UnitType Unit{get;};
  }
}
