namespace RNSVG
{
    [default_interface]
    runtimeclass SvgViewManager
      : Microsoft.ReactNative.IViewManager
      , Microsoft.ReactNative.IViewManagerWithReactContext
      , Microsoft.ReactNative.IViewManagerWithNativeProperties
      , Microsoft.ReactNative.IViewManagerWithChildren
    {
        SvgViewManager();
    }
}
