namespace RNSVG {
  enum SVGClass {
    RNSVGGroup,
    RNSVGPath,
    RNSVGText,
    RNSVGTSpan,
    RNSVGTextPath,
    RNSVGImage,
    RNSVGCircle,
    RNSVGEllipse,
    RNSVGLine,
    RNSVGRect,
    RNSVGClipPath,
    RNSVGDefs,
    RNSVGUse,
    RNSVGSymbol,
    RNSVGLinearGradient,
    RNSVGRadialGradient,
    RNSVGPattern,
    RNSVGMask,
    RNSVGMarker,
    RNSVGForeignObject,
    Unknown,
  };

  enum MeetOrSlice {
    Meet,
    Slice,
    None,
  };

  enum BaseProp {
    Matrix,
    Fill,
    FillOpacity,
    FillRule,
    Stroke,
    StrokeOpacity,
    StrokeWidth,
    StrokeMiterLimit,
    StrokeDashOffset,
    StrokeDashArray,
    StrokeLineCap,
    StrokeLineJoin,
    Unknown,
  };

  enum FontProp {
    FontSize,
    FontWeight,
    FontFamily,
    Unknown,
  };

  enum LengthType
  {
    Unknown,
    Number,
    Percentage,
    EMS,
    EXS,
    Pixel,
    Centimeter,
    Millimeter,
    Inch,
    Point,
    Pica,
  };

  [default_interface]
  runtimeclass SVGLength {
    SVGLength();
    SVGLength(Single param);
    SVGLength(Single param, LengthType type);

    Single Value{ get; };
    LengthType Unit{ get; };
  };
}
