namespace RNSVG
{
  [experimental]
  [default_interface]
  unsealed runtimeclass SvgNodeCommonProps : Microsoft.ReactNative.IComponentProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass SvgRenderableCommonProps : SvgNodeCommonProps {
  };

  [experimental]
  [default_interface]
  runtimeclass SvgViewProps : Microsoft.ReactNative.IComponentProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass RectProps : SvgRenderableCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass CircleProps : SvgRenderableCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass EllipseProps : SvgRenderableCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass LineProps : SvgRenderableCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass PathProps : SvgRenderableCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass UseProps : SvgRenderableCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass SymbolProps : SvgRenderableCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass ImageProps : SvgRenderableCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass SvgGroupCommonProps : SvgRenderableCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass DefsProps : SvgGroupCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass ClipPathProps : SvgGroupCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass MarkerProps : SvgGroupCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass MaskProps : SvgGroupCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass LinearGradientProps : SvgGroupCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass RadialGradientProps : SvgGroupCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass PatternProps : SvgGroupCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass SvgTextCommonProps : SvgGroupCommonProps {
  };

  [experimental]
  [default_interface]
  unsealed runtimeclass TSpanProps : SvgTextCommonProps {
  };
}