name: Test iOS e2e
on:
  pull_request:
    paths:
      - '.github/workflows/ios-e2e.yml'
      - 'apps/examples/**'
      - 'apple/**'
      - 'src/**'
      - 'e2e/**'
      - 'package.json'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14
    timeout-minutes: 60
    env:
      WORKING_DIRECTORY: example
      DEVICE: iPhone 16 Pro
      XCODE_VERSION: latest-stable
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Use latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Get yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install react-native-svg node_modules
        run: yarn install --frozen-lockfile

      - name: Install app node_modules
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn install --frozen-lockfile

      - name: Get Pods cache
        uses: actions/cache@v4
        with:
          path: ${{ env.WORKING_DIRECTORY }}/ios/Pods
          key: ${{ runner.os }}-pods-${{ env.WORKING_DIRECTORY }}-${{ hashFiles(format('{0}/ios/Podfile.lock', env.WORKING_DIRECTORY)) }}
          restore-keys: |
            ${{ runner.os }}-pods-${{ env.WORKING_DIRECTORY }}-

      - name: Install Pods
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: bundle install && bundle exec pod install

      - name: Get build artifacts cache
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-ios-derived-data-${{ env.WORKING_DIRECTORY }}-${{ hashFiles(format('{0}/ios/Podfile.lock', env.WORKING_DIRECTORY)) }}
          restore-keys: |
            ${{ runner.os }}-ios-derived-data-${{ env.WORKING_DIRECTORY }}-

      - name: Start Metro server
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: E2E=true yarn start &> output.log &

      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: E2E=true npx react-native@latest run-ios --simulator="${{ env.DEVICE }}" --mode Debug --verbose

      - name: Run e2e Tests
        run: E2E=true yarn e2e

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: |
            report.html
            jest-html-reporters-attach/
