ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

def is_ci_enabled?
  %w[1 true].include?(ENV['CI'].to_s.downcase)
end

# ENV['DISABLE_RNREPO'] = "1" # Uncomment to disable RNRepo even in CI
def is_rnrepo_enabled?
  ENV['DISABLE_RNREPO'].nil?
end

# Use RNRepo in CI builds. Set DISABLE_RNREPO to any value to disable RNRepo.
if is_ci_enabled? && is_rnrepo_enabled?
  require Pod::Executable.execute_command('node', ['-p',
    'require.resolve(
      "@rnrepo/build-tools/cocoapods-plugin/lib/plugin.rb",
      {paths: [process.argv[1]]},
    )', __dir__]).strip
end

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FabricExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    if is_ci_enabled? && is_rnrepo_enabled?
      rnrepo_post_install(installer)
    end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
